(()=>{
  if(window.__dmAdminToolboxLoaded)return;window.__dmAdminToolboxLoaded=true;
  const API='https://wutlhceqkioshepfbykf.supabase.co/functions/v1/damion-admin-toolbox';
  const OWNER_SESSION_KEY='damion_site_session';
  let enteredKey='';let unlocked=false;let eventTimer=null;let pollTimer=null;
  const ownerSession=()=>{try{return localStorage.getItem(OWNER_SESSION_KEY)||''}catch(_){return''}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const post=async(action,extra={})=>{const r=await fetch(API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d};

  const style=document.createElement('style');style.id='dm-admin-toolbox-style';style.textContent=`
    #dmAdminUnlockBg{position:fixed;inset:0;z-index:2100;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.6);backdrop-filter:blur(8px);opacity:0;pointer-events:none;transition:.16s ease}#dmAdminUnlockBg.open{opacity:1;pointer-events:auto}.dm-at-unlock{width:min(350px,100%);padding:18px;border:1px solid rgba(255,255,255,.11);border-radius:16px;background:linear-gradient(180deg,#15161a,#0b0c0e);box-shadow:0 28px 80px rgba(0,0,0,.6);color:#fff}.dm-at-unlock-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.dm-at-unlock h3{margin:0;font-size:19px}.dm-at-unlock p{margin:7px 0 14px;color:#8e929a;font-size:11px;line-height:1.5}.dm-at-close{width:31px;height:31px;border-radius:9px;border:1px solid rgba(255,255,255,.09);background:#17191d;color:#fff;cursor:pointer}.dm-at-unlock form{display:grid;gap:9px}.dm-at-unlock input,.dm-at-unlock select,.dm-admin-toolbox input,.dm-admin-toolbox textarea,.dm-admin-toolbox select{width:100%;border:1px solid rgba(255,255,255,.09);background:#111317;color:#fff;border-radius:9px;padding:9px 10px;outline:none;font:inherit;font-size:11px}.dm-at-unlock input{min-height:43px}.dm-at-status{min-height:15px;color:#7f848c;font-size:10px}.dm-at-status.error{color:#ff7188}.dm-at-login-link{display:none;margin-top:3px;color:#ff6b7e;font-size:10px;text-decoration:none}.dm-at-login-link.show{display:inline-block}
    .dm-admin-toolbox{position:fixed;right:22px;top:120px;z-index:2050;width:318px;max-height:76vh;display:none;overflow:hidden;border:1px solid rgba(255,255,255,.11);border-radius:15px;background:linear-gradient(180deg,rgba(18,19,23,.985),rgba(8,9,11,.985));box-shadow:0 24px 70px rgba(0,0,0,.6);color:#f5f5f7;font:11px/1.35 Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.dm-admin-toolbox.open{display:block}.dm-at-head{height:46px;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 10px 0 12px;border-bottom:1px solid rgba(255,255,255,.07);cursor:grab;user-select:none;touch-action:none}.dm-at-head:active{cursor:grabbing}.dm-at-brand{display:flex;align-items:center;gap:8px}.dm-at-brand i{width:7px;height:7px;border-radius:50%;background:#ff3e5f;box-shadow:0 0 10px rgba(255,62,95,.7)}.dm-at-brand b{font-size:11px}.dm-at-brand span{display:block;color:#696e77;font-size:8px;text-transform:uppercase;letter-spacing:.08em}.dm-at-head-actions{display:flex;gap:5px}.dm-at-head-actions button{width:28px;height:28px;border:1px solid rgba(255,255,255,.08);border-radius:8px;background:#15171a;color:#aeb2b9;cursor:pointer}.dm-at-body{max-height:calc(76vh - 46px);overflow:auto;padding:11px}.dm-at-section{padding:10px;border:1px solid rgba(255,255,255,.065);border-radius:11px;background:rgba(255,255,255,.018);margin-bottom:9px}.dm-at-section:last-child{margin-bottom:0}.dm-at-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.dm-at-title b{font-size:10px;text-transform:uppercase;letter-spacing:.06em}.dm-at-title span{color:#696e77;font-size:8px}.dm-at-row{display:flex;gap:7px}.dm-at-row>*{flex:1}.dm-at-btn{min-height:34px;border:1px solid rgba(255,255,255,.08);border-radius:9px;background:#15171a;color:#dddfe4;padding:0 10px;cursor:pointer;font-weight:850;font-size:10px}.dm-at-btn:hover{border-color:rgba(239,79,95,.3);background:#191b1f}.dm-at-btn.primary{background:#ed405b;border-color:#ed405b;color:#fff}.dm-at-btn.danger{color:#ff778a}.dm-at-form{display:grid;gap:7px}.dm-admin-toolbox textarea{min-height:58px;max-height:120px;resize:vertical}.dm-at-mini{color:#737881;font-size:9px;line-height:1.45}.dm-at-success{color:#6fdfa0}.dm-at-event-status{margin-top:7px;min-height:14px;color:#858a92;font-size:9px}.dm-at-collapsed .dm-at-body{display:none}.dm-at-collapsed{max-height:46px}
    #dmSiteEventBanner{position:fixed;left:50%;top:78px;z-index:1500;width:min(660px,calc(100vw - 26px));transform:translate(-50%,-12px);opacity:0;pointer-events:none;transition:.2s ease;border:1px solid rgba(255,255,255,.1);border-radius:13px;background:linear-gradient(180deg,rgba(24,18,20,.97),rgba(10,10,12,.97));box-shadow:0 16px 55px rgba(0,0,0,.48);color:#fff;padding:10px 12px;font:11px/1.4 Inter,system-ui}.dm-event-on #dmSiteEventBanner{opacity:1;transform:translate(-50%,0);pointer-events:auto}.dm-event-inner{display:flex;align-items:center;gap:11px}.dm-event-badge{flex:0 0 auto;border:1px solid rgba(255,73,99,.28);background:rgba(255,73,99,.08);color:#ff7084;border-radius:999px;padding:5px 7px;font-size:8px;font-weight:950;text-transform:uppercase;letter-spacing:.07em}.dm-event-copy{min-width:0;flex:1}.dm-event-copy b{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dm-event-copy span{display:block;margin-top:2px;color:#9ca0a8;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dm-event-time{flex:0 0 auto;color:#6fdfa0;font-size:9px;font-weight:900}@media(max-width:760px){.dm-admin-toolbox{width:min(318px,calc(100vw - 24px));right:12px;top:92px}#dmSiteEventBanner{top:68px}.dm-event-copy span{white-space:normal}.dm-event-time{display:none}}
  `;document.head.appendChild(style);

  const banner=document.createElement('div');banner.id='dmSiteEventBanner';banner.setAttribute('role','status');banner.innerHTML='<div class="dm-event-inner"><span class="dm-event-badge" id="dmEventBadge">Event</span><div class="dm-event-copy"><b id="dmEventTitle"></b><span id="dmEventMessage"></span></div><span class="dm-event-time" id="dmEventTime"></span></div>';document.body.appendChild(banner);
  const formatLeft=ends=>{const ms=new Date(ends||0).getTime()-Date.now();if(!Number.isFinite(ms)||ms<=0)return'';const m=Math.ceil(ms/60000);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`};
  let currentState=null;
  function renderEvent(state){currentState=state||{};const active=Boolean(state?.active);document.documentElement.classList.toggle('dm-event-on',active);if(!active){if(eventTimer){clearInterval(eventTimer);eventTimer=null}return}document.getElementById('dmEventBadge').textContent=String(state.event_type||'event');document.getElementById('dmEventTitle').textContent=state.title||'Damiønmusic event';document.getElementById('dmEventMessage').textContent=state.message||'';const tick=()=>{const left=formatLeft(state.ends_at);document.getElementById('dmEventTime').textContent=left?`${left} left`:'';if(state.ends_at&&!left){document.documentElement.classList.remove('dm-event-on');if(eventTimer)clearInterval(eventTimer);eventTimer=null}};tick();if(eventTimer)clearInterval(eventTimer);eventTimer=setInterval(tick,30000)}
  async function loadEvent(){try{renderEvent(await post('public_state'))}catch(_){}}

  let unlockBg=null,toolbox=null;
  function buildUnlock(){if(unlockBg)return;unlockBg=document.createElement('div');unlockBg.id='dmAdminUnlockBg';unlockBg.innerHTML=`<section class="dm-at-unlock" role="dialog" aria-modal="true" aria-label="Admin toolbox unlock"><div class="dm-at-unlock-head"><h3>Admin toolbox</h3><button class="dm-at-close" type="button" aria-label="Close">×</button></div><p>Private owner shortcut. Enter your toolbox key to continue.</p><form><input name="key" type="password" inputmode="numeric" maxlength="12" autocomplete="off" placeholder="Admin key" required><button class="dm-at-btn primary" type="submit">Unlock</button><div class="dm-at-status" aria-live="polite"></div><a class="dm-at-login-link" href="/admin-orders">Open owner sign in</a></form></section>`;document.body.appendChild(unlockBg);const close=()=>unlockBg.classList.remove('open');unlockBg.addEventListener('pointerdown',e=>{if(e.target===unlockBg)close()});unlockBg.querySelector('.dm-at-close').addEventListener('click',close);const form=unlockBg.querySelector('form'),status=unlockBg.querySelector('.dm-at-status'),loginLink=unlockBg.querySelector('.dm-at-login-link');form.addEventListener('submit',async e=>{e.preventDefault();const key=String(form.elements.key.value||'').trim();if(!key)return;const session=ownerSession();status.className='dm-at-status';loginLink.classList.remove('show');if(!session){status.className='dm-at-status error';status.textContent='Owner sign-in required first.';loginLink.classList.add('show');return}const btn=form.querySelector('button[type="submit"]');btn.disabled=true;status.textContent='Checking owner access…';try{await post('unlock',{ownerSession:session,key});enteredKey=key;unlocked=true;status.className='dm-at-status dm-at-success';status.textContent='Unlocked';setTimeout(()=>{close();openToolbox()},130)}catch(err){enteredKey='';unlocked=false;status.className='dm-at-status error';status.textContent=err.message||'Could not unlock';if(/owner session/i.test(status.textContent))loginLink.classList.add('show')}finally{btn.disabled=false;form.elements.key.value=''}})}
  function openUnlock(){buildUnlock();unlockBg.classList.add('open');setTimeout(()=>unlockBg.querySelector('input')?.focus({preventScroll:true}),70)}

  function buildToolbox(){if(toolbox)return;toolbox=document.createElement('aside');toolbox.className='dm-admin-toolbox';toolbox.innerHTML=`<div class="dm-at-head"><div class="dm-at-brand"><i></i><div><b>Damiønmusic Admin</b><span>Owner toolbox</span></div></div><div class="dm-at-head-actions"><button data-min type="button" title="Minimize">−</button><button data-close type="button" title="Close">×</button></div></div><div class="dm-at-body"><section class="dm-at-section"><div class="dm-at-title"><b>Live site</b><span>Private</span></div><div class="dm-at-row"><button class="dm-at-btn" data-visitors type="button">Live visitors</button><button class="dm-at-btn" data-dashboard type="button">Full dashboard</button></div></section><section class="dm-at-section"><div class="dm-at-title"><b>Giveaway / event</b><span>Shows site-wide</span></div><form class="dm-at-form" id="dmAdminEventForm"><select name="event_type"><option value="giveaway">Giveaway</option><option value="event">Event</option><option value="announcement">Announcement</option></select><input name="title" maxlength="100" placeholder="Title e.g. Free Mix Giveaway"><textarea name="message" maxlength="400" placeholder="Message visitors will see"></textarea><select name="minutes"><option value="10">10 minutes</option><option value="30" selected>30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option><option value="240">4 hours</option></select><button class="dm-at-btn primary" type="submit">Start live event</button></form><div class="dm-at-event-status" id="dmAdminEventStatus"></div><div class="dm-at-row" style="margin-top:7px"><button class="dm-at-btn danger" data-clear type="button">Stop current event</button></div></section><section class="dm-at-section"><div class="dm-at-title"><b>Quick tools</b><span>Owner only</span></div><div class="dm-at-mini">Drag this panel by its top bar. Close it anytime. Press <b>A</b> again to reopen it after unlocking.</div></section></div>`;document.body.appendChild(toolbox);
    toolbox.querySelector('[data-close]').addEventListener('click',()=>toolbox.classList.remove('open'));toolbox.querySelector('[data-min]').addEventListener('click',()=>toolbox.classList.toggle('dm-at-collapsed'));toolbox.querySelector('[data-dashboard]').addEventListener('click',()=>location.href='/admin-orders');toolbox.querySelector('[data-visitors]').addEventListener('click',()=>{const live=document.getElementById('dmLiveVisitors');if(live){live.classList.add('open');live.scrollIntoView?.({block:'nearest'})}});
    const status=toolbox.querySelector('#dmAdminEventStatus'),form=toolbox.querySelector('#dmAdminEventForm');form.addEventListener('submit',async e=>{e.preventDefault();if(!unlocked||!enteredKey)return openUnlock();const btn=form.querySelector('button[type="submit"]');btn.disabled=true;status.textContent='Starting event…';try{const out=await post('set_event',{ownerSession:ownerSession(),key:enteredKey,event_type:form.elements.event_type.value,title:form.elements.title.value,message:form.elements.message.value,minutes:Number(form.elements.minutes.value)});status.className='dm-at-event-status dm-at-success';status.textContent='Event is live for visitors.';renderEvent(out.state);setTimeout(loadEvent,400)}catch(err){status.className='dm-at-event-status';status.textContent=err.message||'Could not start event'}finally{btn.disabled=false}});toolbox.querySelector('[data-clear]').addEventListener('click',async()=>{if(!unlocked||!enteredKey)return openUnlock();status.textContent='Stopping event…';try{await post('clear_event',{ownerSession:ownerSession(),key:enteredKey});status.className='dm-at-event-status dm-at-success';status.textContent='Event stopped.';renderEvent({active:false})}catch(err){status.className='dm-at-event-status';status.textContent=err.message||'Could not stop event'}});
    makeDraggable(toolbox,toolbox.querySelector('.dm-at-head'));
  }
  function openToolbox(){if(!unlocked)return openUnlock();buildToolbox();toolbox.classList.add('open')}
  function makeDraggable(el,handle){let drag=null;handle.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const r=el.getBoundingClientRect();drag={id:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top};handle.setPointerCapture?.(e.pointerId);el.style.right='auto';el.style.bottom='auto';e.preventDefault()});handle.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const w=el.offsetWidth,h=el.offsetHeight;const x=Math.max(6,Math.min(window.innerWidth-w-6,e.clientX-drag.dx));const y=Math.max(6,Math.min(window.innerHeight-Math.min(h,60)-6,e.clientY-drag.dy));el.style.left=x+'px';el.style.top=y+'px'});const end=e=>{if(drag&&e.pointerId===drag.id){drag=null;try{handle.releasePointerCapture?.(e.pointerId)}catch(_){}}};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end)}

  document.addEventListener('keydown',e=>{if(e.key.toLowerCase()!=='a'||e.ctrlKey||e.metaKey||e.altKey)return;const t=e.target;if(t&&(t.matches?.('input,textarea,select')||t.isContentEditable))return;e.preventDefault();if(unlocked)openToolbox();else openUnlock()});
  loadEvent();pollTimer=setInterval(()=>{if(document.visibilityState==='visible')loadEvent()},10000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')loadEvent()});window.addEventListener('pagehide',()=>{if(pollTimer)clearInterval(pollTimer);if(eventTimer)clearInterval(eventTimer)},{once:true});
})();
