(()=>{
  const AUTH_API='https://wutlhceqkioshepfbykf.supabase.co/functions/v1/damion-site-auth';
  const ORDER_API='https://wutlhceqkioshepfbykf.supabase.co/functions/v1/damion-orders';
  const SUPPORT_API='https://wutlhceqkioshepfbykf.supabase.co/functions/v1/damion-support';
  const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dGxoY2Vxa2lvc2hlcGZieWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMDAxMDUsImV4cCI6MjEwMTU3NjEwNX0.Ad9wROEhZ2uKxKx9H5AHqCCmFa0nTezrBHkAn-Zwyws';
  const OWNER_EMAIL='damianschenk234@gmail.com';
  const OWNER_SESSION_KEY='damion_site_session';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const eur=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
  let ownerSession='';let timer=null;let knownOrders=new Set();let supportChats=[];let activeTicket='';let knownSupport=new Map();let promoRows=[];

  async function authApi(action,extra={}){const res=await fetch(AUTH_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Login failed');return data}
  async function api(url,action,extra={}){const res=await fetch(url,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':`Bearer ${ANON}`},body:JSON.stringify({action,ownerSession,...extra})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
  const callOrders=(action,extra={})=>api(ORDER_API,action,extra);
  const callSupport=(action,extra={})=>api(SUPPORT_API,action,extra);

  function renderOrders(orders){const host=$('orders');if(!host)return;if(!orders.length){host.innerHTML='<div class="empty">No orders yet.</div>';return}host.innerHTML=orders.map(o=>`<article class="order-row" data-ref="${esc(o.order_number)}"><div><span class="order-id">${esc(o.order_number)}</span><small>${new Date(o.created_at).toLocaleString()}</small></div><div><span class="order-project">${esc(o.project_name)}</span><small>${esc(o.customer_name)} · ${esc(o.customer_email)}</small></div><div><b>${esc(o.service_name)}</b><small>${esc(o.package_name||'')}</small></div><div class="order-total">${eur(o.amount_eur)}</div><div class="order-status">${esc(o.status||'Paid')}</div></article>`).join('')}
  function stats(orders){$('statTotal').textContent=orders.length;$('statActive').textContent=orders.filter(o=>!['Completed','Cancelled','Refunded'].includes(o.status)).length;$('statDone').textContent=orders.filter(o=>o.status==='Completed').length;$('statRevenue').textContent=eur(orders.reduce((s,o)=>s+Number(o.amount_eur||0),0))}
  function notifyNewOrders(orders){const fresh=orders.filter(o=>!knownOrders.has(o.order_number));if(knownOrders.size&&fresh.length&&'Notification'in window&&Notification.permission==='granted')new Notification('New Damiønmusic order',{body:`${fresh[0].order_number} · ${fresh[0].project_name}`});knownOrders=new Set(orders.map(o=>o.order_number))}
  function rememberOwnerSession(token){try{localStorage.setItem(OWNER_SESSION_KEY,token)}catch(_){}}
  function forgetOwnerSession(){try{localStorage.removeItem(OWNER_SESSION_KEY);localStorage.removeItem('dm_admin_key_saved');sessionStorage.removeItem('dm_admin_key')}catch(_){}}

  async function refreshOrders(){if(!ownerSession)return;try{const data=await callOrders('admin_list');const orders=data.orders||[];notifyNewOrders(orders);stats(orders);renderOrders(orders);$('dashStatus').textContent='';$('lastCheck').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(err){$('dashStatus').textContent=err.message||'Could not load orders';$('dashStatus').classList.add('error')}}
  function supportPreview(chat){return chat.last_message?.message||'No message preview'}
  function supportTime(chat){const iso=chat.last_message?.created_at||chat.updated_at||chat.created_at;try{return new Date(iso).toLocaleString([],{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}catch(_){return''}}
  function renderSupportThreads(){const host=$('supportThreads');if(!host)return;$('supportCount').textContent=String(supportChats.filter(c=>c.status==='open').length);if(!supportChats.length){host.innerHTML='<div class="support-empty">No support chats yet.</div>';return}host.innerHTML=supportChats.map(c=>`<button type="button" class="support-thread${activeTicket===c.ticket_number?' active':''}" data-ticket="${esc(c.ticket_number)}"><div class="support-thread-top"><span class="support-thread-name">${esc(c.name)}</span><span class="support-thread-status ${esc(c.status||'open')}">${esc(c.status||'open')}</span></div><div class="support-thread-preview">${c.last_message?.sender==='staff'?'You: ':''}${esc(supportPreview(c))}</div><div class="support-thread-meta">${esc(c.ticket_number)} · ${esc(supportTime(c))}</div></button>`).join('');host.querySelectorAll('.support-thread').forEach(btn=>btn.addEventListener('click',()=>openSupport(btn.dataset.ticket)))}
  function notifySupport(chats){const changed=[];for(const c of chats){const stamp=c.last_message?.created_at||c.updated_at||'';const prev=knownSupport.get(c.ticket_number);if(knownSupport.size&&stamp&&prev&&stamp!==prev&&c.last_message?.sender==='customer')changed.push(c);knownSupport.set(c.ticket_number,stamp)}if(changed.length&&'Notification'in window&&Notification.permission==='granted')new Notification('New support message',{body:`${changed[0].name}: ${supportPreview(changed[0]).slice(0,90)}`})}
  async function refreshSupport(openActive=false){if(!ownerSession)return;try{const data=await callSupport('admin_list');supportChats=data.chats||[];notifySupport(supportChats);renderSupportThreads();$('supportAdminStatus').textContent='';$('supportAdminStatus').classList.remove('error');$('supportLastCheck').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(openActive&&activeTicket)await openSupport(activeTicket,true)}catch(err){$('supportAdminStatus').textContent=err.message||'Could not load support chats';$('supportAdminStatus').classList.add('error')}}
  function promoDiscountLabel(p){return p.discount_type==='percent'?Number(p.discount_value||0).toFixed(Number(p.discount_value)%1?1:0)+'%':eur(p.discount_value)}
  function renderGrowth(data){
    const refs=data.referrals||{};$('growthClicks').textContent=String(Number(refs.clicks||0));$('growthSignups').textContent=String(Number(refs.signups||0));$('growthPaid').textContent=String(Number(refs.paid_orders||0));$('growthRewards').textContent=eur(refs.rewards||0);
    promoRows=data.promos||[];const host=$('promoList');if(!host)return;
    if(!promoRows.length){host.innerHTML='<div class="empty">No promo codes yet. Create your first code above.</div>';return}
    host.innerHTML=promoRows.map(p=>`<article class="promo-row"><div><b>${esc(p.code)}</b><small>${esc(p.description||p.source||'Promo code')}</small></div><div class="promo-chip">${esc(promoDiscountLabel(p))}</div><div><b>${esc(String(p.uses_count||0))}${p.max_uses!=null?' / '+esc(String(p.max_uses)):''}</b><small>uses</small></div><div><b>${Number(p.min_order_eur||0)>0?eur(p.min_order_eur):'Any'}</b><small>minimum</small></div><div class="promo-state"><b>${p.active?'Active':'Inactive'}</b><small>${p.expires_at?'Expires '+new Date(p.expires_at).toLocaleDateString():'No expiry'} · ${esc(p.source||'manual')}</small></div><button class="promo-toggle ${p.active?'':'off'}" type="button" data-promo-toggle="${esc(p.code)}" data-next="${p.active?'0':'1'}">${p.active?'Disable':'Enable'}</button></article>`).join('');
    host.querySelectorAll('[data-promo-toggle]').forEach(btn=>btn.addEventListener('click',async()=>{btn.disabled=true;try{await authApi('promo_admin_toggle',{session_token:ownerSession,code:btn.dataset.promoToggle,active:btn.dataset.next==='1'});await refreshGrowth()}catch(err){$('promoAdminStatus').textContent=err.message||'Could not update promo';$('promoAdminStatus').classList.add('error')}finally{btn.disabled=false}}));
  }
  async function refreshGrowth(){
    if(!ownerSession)return;
    try{const data=await authApi('promo_admin_list',{session_token:ownerSession});renderGrowth(data);$('promoAdminStatus').classList.remove('error')}catch(err){$('promoAdminStatus').textContent=err.message||'Could not load promo codes';$('promoAdminStatus').classList.add('error')}
  }

  function renderConversation(data){const box=$('supportConversation');if(!box)return;const c=data.chat||{},messages=data.messages||[];box.innerHTML=`<div class="support-convo-head"><div><b>${esc(c.name||'Customer')}</b><small>${esc(c.email||'')} · ${esc(c.ticket_number||'')}</small></div><button id="closeSupportChat" type="button">${c.status==='closed'?'Closed':'Close chat'}</button></div><div class="support-convo-messages" id="supportMessages">${messages.map(m=>`<div class="support-message ${m.sender==='staff'?'staff':'customer'}"><span>${m.sender==='staff'?'You':'Customer'}</span><p>${esc(m.message)}</p><small>${new Date(m.created_at).toLocaleString([],{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="support-empty">No messages.</div>'}</div><form id="supportReplyForm" class="support-reply"><textarea name="message" maxlength="4000" required placeholder="Write your reply..."></textarea><button class="btn primary" type="submit">Reply</button><div class="status-line" aria-live="polite"></div></form>`;const list=$('supportMessages');if(list)list.scrollTop=list.scrollHeight;const closeBtn=$('closeSupportChat');if(c.status==='closed')closeBtn.disabled=true;else closeBtn.addEventListener('click',async()=>{closeBtn.disabled=true;try{const out=await callSupport('admin_close',{ticket:c.ticket_number});renderConversation(out);await refreshSupport()}catch(err){$('supportAdminStatus').textContent=err.message||'Could not close chat';closeBtn.disabled=false}});const form=$('supportReplyForm');form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const btn=form.querySelector('button'),status=form.querySelector('.status-line'),message=form.elements.message.value;btn.disabled=true;status.textContent='Sending reply…';status.classList.remove('error');try{const out=await callSupport('admin_reply',{ticket:c.ticket_number,message});form.elements.message.value='';renderConversation(out);await refreshSupport()}catch(err){status.textContent=err.message||'Could not send reply';status.classList.add('error')}finally{btn.disabled=false}})}
  async function openSupport(ticket,silent=false){activeTicket=String(ticket||'');renderSupportThreads();if(!activeTicket)return;if(!silent)$('supportConversation').innerHTML='<div class="support-empty">Loading conversation…</div>';try{renderConversation(await callSupport('admin_get',{ticket:activeTicket}))}catch(err){$('supportConversation').innerHTML=`<div class="support-empty">${esc(err.message||'Could not open conversation')}</div>`}}
  async function refreshAll(){if(!ownerSession)return;$('dashStatus').textContent='Refreshing…';$('dashStatus').classList.remove('error');await Promise.all([refreshOrders(),refreshSupport(Boolean(activeTicket)),refreshGrowth()]);$('dashStatus').textContent=''}
  function showDashboard(){ $('loginCard').classList.add('hidden');$('dashboard').classList.remove('hidden');$('miniAdminBtn')?.classList.remove('hidden');$('viewSiteBtn')?.classList.remove('hidden');$('logoutBtn')?.classList.remove('hidden');$('loginStatus').textContent='';$('liveText').textContent='Private dashboard + live visitor view active';window.dispatchEvent(new CustomEvent('dm-owner-ready'));if(timer)clearInterval(timer);timer=setInterval(()=>{if(document.visibilityState==='visible')refreshAll()},12000)}

  async function login(password){password=String(password||'');if(!password)return;$('loginStatus').textContent='Checking…';$('loginStatus').classList.remove('error');try{const out=await authApi('owner_login',{email:OWNER_EMAIL,password});ownerSession=out.session_token;rememberOwnerSession(ownerSession);showDashboard();await refreshAll()}catch(err){ownerSession='';forgetOwnerSession();$('loginStatus').textContent=err.message||'Admin password is incorrect';$('loginStatus').classList.add('error')}finally{if($('adminKey'))$('adminKey').value=''}}
  async function resume(token){try{const session=await authApi('session',{session_token:token});if(!session.authenticated||!session.is_owner)throw new Error('Owner session expired');ownerSession=token;showDashboard();await refreshAll()}catch(_){ownerSession='';forgetOwnerSession()}}

  $('loginForm')?.addEventListener('submit',e=>{e.preventDefault();login($('adminKey').value)});
  $('promoCreateForm')?.addEventListener('submit',async e=>{
    e.preventDefault();const form=e.currentTarget;if(!form.reportValidity()||!ownerSession)return;
    const btn=form.querySelector('button[type="submit"]');btn.disabled=true;$('promoAdminStatus').textContent='Creating promo…';$('promoAdminStatus').classList.remove('error');
    try{
      const expiry=$('promoAdminExpiry').value;
      await authApi('promo_admin_create',{session_token:ownerSession,code:$('promoAdminCode').value,description:$('promoAdminDescription').value,discount_type:$('promoAdminType').value,discount_value:Number($('promoAdminValue').value),min_order_eur:Number($('promoAdminMin').value||0),max_uses:Number($('promoAdminMax').value||0),expires_at:expiry?new Date(expiry).toISOString():''});
      $('promoAdminStatus').textContent='Promo code created.';form.reset();$('promoAdminType').value='percent';$('promoAdminValue').value='10';$('promoAdminMin').value='0';await refreshGrowth();
    }catch(err){$('promoAdminStatus').textContent=err.message||'Could not create promo code';$('promoAdminStatus').classList.add('error')}finally{btn.disabled=false}
  });
  $('promoAdminCode')?.addEventListener('input',e=>{e.target.value=String(e.target.value||'').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,40)});
  $('refreshBtn')?.addEventListener('click',refreshAll);
  $('notifyBtn')?.addEventListener('click',async()=>{if(!('Notification'in window))return alert('Browser notifications are not supported here.');const p=await Notification.requestPermission();$('notifyBtn').textContent=p==='granted'?'Notifications enabled':'Notifications blocked'});
  $('logoutBtn')?.addEventListener('click',async()=>{const token=ownerSession;ownerSession='';forgetOwnerSession();try{if(token)await authApi('logout',{session_token:token})}catch(_){}location.reload()});
  window.addEventListener('pagehide',()=>{if(timer)clearInterval(timer)},{once:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&ownerSession)refreshAll()});
  let saved='';try{saved=localStorage.getItem(OWNER_SESSION_KEY)||''}catch(_){}if(saved)resume(saved);
})();
