const ORDER_API='https://wutlhceqkioshepfbykf.supabase.co/functions/v1/damion-orders';
const ORDER_ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dGxoY2Vxa2lvc2hlcGZieWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMDAxMDUsImV4cCI6MjEwMTU3NjEwNX0.Ad9wROEhZ2uKxKx9H5AHqCCmFa0nTezrBHkAn-Zwyws';
const $=id=>document.getElementById(id);let token='',currentOrder=null,currentRating=5;
async function call(action,extra={}){const res=await fetch(ORDER_API,{method:'POST',headers:{'Content-Type':'application/json','apikey':ORDER_ANON,'Authorization':`Bearer ${ORDER_ANON}`},body:JSON.stringify({action,token,...extra})});let data={};try{data=await res.json()}catch(_){}if(!res.ok)throw new Error(data.error||'Could not load order');return data}
function fmtDate(v){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch(_){return v||'—'}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderMessages(list){const box=$('messages');if(!box)return;box.innerHTML=(list||[]).map(m=>`<div class="bubble ${m.sender==='customer'?'customer':''}"><div>${esc(m.message)}</div><small>${m.sender==='customer'?'You':'Damiønmusic'} · ${fmtDate(m.created_at)}</small></div>`).join('')||'<div class="muted">No messages yet.</div>';box.scrollTop=box.scrollHeight}
function renderReview(review){const completed=currentOrder&&(currentOrder.status==='Completed'||Number(currentOrder.progress)>=100);$('reviewText').disabled=!completed;$('reviewButton').disabled=!completed;$('reviewHint').textContent=completed?'Share your experience with Damiønmusic.':'Reviews unlock when the order is completed.';if(review){currentRating=review.rating;$('reviewText').value=review.review;$('reviewStatus').textContent='Your review has been saved.'}document.querySelectorAll('#reviewStars button').forEach(b=>b.classList.toggle('active',Number(b.dataset.rating)<=currentRating))}
function render(data){const o=data.order;currentOrder=o;$('orderEmpty').classList.add('hidden');$('orderRoom').classList.remove('hidden');$('orderNo').textContent=o.order_number;$('projectName').textContent=o.project_name;$('statusPill').textContent=o.status;$('progressBar').style.width=`${Math.max(0,Math.min(100,Number(o.progress)||0))}%`;$('progressText').textContent=`${o.progress}%`;$('etaText').textContent=o.eta_text||'Your order is moving through the studio.';$('serviceName').textContent=o.service_name||'—';$('packageName').textContent=o.package_name||'—';$('deliveryFormat').textContent=o.delivery_format||'Audio files';$('amountPaid').textContent=`€${Number(o.amount_eur||0).toFixed(2)}`;$('customerName').textContent=o.customer_name;$('customerEmail').textContent=o.customer_email;$('createdAt').textContent=fmtDate(o.created_at);$('paypalRef').textContent=o.paypal_order_id||'—';document.querySelectorAll('.time-step').forEach(el=>el.classList.toggle('done',Number(o.progress)>=Number(el.dataset.step)));const dl=$('downloadBox'),btn=$('downloadButton');if(o.download_url){dl.classList.remove('locked');$('downloadHelp').textContent='Your final files are ready.';$('downloadLabel').textContent=o.download_label||o.delivery_format||'Final delivery';btn.href=o.download_url;btn.classList.remove('hidden')}else{dl.classList.add('locked');btn.classList.add('hidden');$('downloadHelp').textContent='Your download unlocks when the order is completed.'}renderMessages(data.messages);renderReview(data.review)}
async function loadOrder(){token=(new URLSearchParams(location.search).get('token')||$('tokenInput')?.value||localStorage.getItem('damion_order_token')||'').trim();if(!token)return;try{$('tokenInput').value=token;const data=await call('get');localStorage.setItem('damion_order_token',token);render(data)}catch(err){$('orderRoom').classList.add('hidden');$('orderEmpty').classList.remove('hidden');$('orderEmpty').innerHTML=`<h2>We couldn't open that order</h2><p>${esc(err.message)}</p>`}}
$('lookupForm')?.addEventListener('submit',e=>{e.preventDefault();token=$('tokenInput').value.trim();if(token)location.href=`/order?token=${encodeURIComponent(token)}`});
$('messageForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=$('messageInput'),message=input.value.trim();if(!message)return;const btn=e.submitter;btn.disabled=true;try{await call('message',{message});input.value='';const data=await call('get');renderMessages(data.messages)}catch(err){alert(err.message)}finally{btn.disabled=false}});
document.querySelectorAll('#reviewStars button').forEach(b=>b.addEventListener('click',()=>{if($('reviewText').disabled)return;currentRating=Number(b.dataset.rating);document.querySelectorAll('#reviewStars button').forEach(x=>x.classList.toggle('active',Number(x.dataset.rating)<=currentRating))}));
$('reviewButton')?.addEventListener('click',async()=>{const text=$('reviewText').value.trim();$('reviewButton').disabled=true;try{await call('review',{rating:currentRating,review:text});$('reviewStatus').textContent='Thanks — your review was saved.'}catch(err){$('reviewStatus').textContent=err.message}finally{$('reviewButton').disabled=false}});
loadOrder();