const ORDER_API='https://wutlhceqkioshepfbykf.supabase.co/functions/v1/damion-orders';
const ORDER_ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dGxoY2Vxa2lvc2hlcGZieWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMDAxMDUsImV4cCI6MjEwMTU3NjEwNX0.Ad9wROEhZ2uKxKx9H5AHqCCmFa0nTezrBHkAn-Zwyws';
const $=id=>document.getElementById(id);let token='',currentOrder=null,currentRating=5,paymentPoll=null;
const isNL=()=>{try{return window.dmGetLanguage&&window.dmGetLanguage()==='nl'}catch(_){return document.documentElement.lang==='nl'}};
const t=(en,nl)=>isNL()?nl:en;
async function call(action,extra={}){const res=await fetch(ORDER_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','apikey':ORDER_ANON,'Authorization':`Bearer ${ORDER_ANON}`,'Cache-Control':'no-cache'},body:JSON.stringify({action,token,...extra})});let data={};try{data=await res.json()}catch(_){}if(!res.ok)throw new Error(data.error||t('Could not load order','Bestelling kon niet worden geladen'));return data}
function fmtDate(v){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch(_){return v||'—'}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function displayStatus(v){const map={'Pending payment':['Pending payment','Wacht op betaling'],'Paid':['Paid','Betaald'],'Payment failed':['Payment failed','Betaling mislukt'],'In production':['In production','In productie'],'Completed':['Completed','Voltooid']};const pair=map[v];return pair?(isNL()?pair[1]:pair[0]):v||'—'}
function displayEta(v){const map={'Waiting for iDEAL payment.':['Waiting for iDEAL payment.','Wachten op iDEAL-betaling.'],'Waiting for iDEAL payment confirmation.':['Waiting for iDEAL payment confirmation.','Wachten op bevestiging van de iDEAL-betaling.'],'iDEAL payment received. Your project is waiting for review.':['iDEAL payment received. Your project is waiting for review.','iDEAL-betaling ontvangen. Je project wacht op controle.'],'The iDEAL payment was not completed. Please start a new order if you still want to continue.':['The iDEAL payment was not completed. Please start a new order if you still want to continue.','De iDEAL-betaling is niet voltooid. Start een nieuwe bestelling als je alsnog wilt doorgaan.']};const pair=map[v];return pair?(isNL()?pair[1]:pair[0]):v||t('Your order is moving through the studio.','Je bestelling wordt verwerkt in de studio.')}
function renderMessages(list){const box=$('messages');if(!box)return;box.innerHTML=(list||[]).map(m=>`<div class="bubble ${m.sender==='customer'?'customer':''}"><div>${esc(m.message)}</div><small>${m.sender==='customer'?t('You','Jij'):'Damiønmusic'} · ${fmtDate(m.created_at)}</small></div>`).join('')||`<div class="muted">${t('No messages yet.','Nog geen berichten.')}</div>`;box.scrollTop=box.scrollHeight}
function renderReview(review){const completed=currentOrder&&(currentOrder.status==='Completed'||Number(currentOrder.progress)>=100);$('reviewText').disabled=!completed;$('reviewButton').disabled=!completed;$('reviewHint').textContent=completed?t('Share your experience with Damiønmusic.','Deel je ervaring met Damiønmusic.'):t('Reviews unlock when the order is completed.','Beoordelingen worden beschikbaar wanneer de bestelling is voltooid.');if(review){currentRating=review.rating;$('reviewText').value=review.review;$('reviewStatus').textContent=t('Your review has been saved.','Je beoordeling is opgeslagen.')}document.querySelectorAll('#reviewStars button').forEach(b=>b.classList.toggle('active',Number(b.dataset.rating)<=currentRating))}
function render(data){const o=data.order;currentOrder=o;$('orderEmpty').classList.add('hidden');$('orderRoom').classList.remove('hidden');$('orderNo').textContent=o.order_number;$('projectName').textContent=o.project_name;$('statusPill').textContent=displayStatus(o.status);$('progressBar').style.width=`${Math.max(0,Math.min(100,Number(o.progress)||0))}%`;$('progressText').textContent=`${o.progress}%`;$('etaText').textContent=displayEta(o.eta_text);$('serviceName').textContent=o.service_name||'—';$('packageName').textContent=o.package_name||'—';$('deliveryFormat').textContent=o.delivery_format||t('Audio files','Audiobestanden');$('amountPaid').textContent=`€${Number(o.amount_eur||0).toFixed(2)}`;$('customerName').textContent=o.customer_name;$('customerEmail').textContent=o.customer_email;$('createdAt').textContent=fmtDate(o.created_at);const paymentRef=$('paymentRef')||$('paypalRef');if(paymentRef)paymentRef.textContent=o.mollie_payment_id||'—';document.querySelectorAll('.time-step').forEach(el=>el.classList.toggle('done',Number(o.progress)>=Number(el.dataset.step)));const dl=$('downloadBox'),btn=$('downloadButton');if(o.download_url){dl.classList.remove('locked');$('downloadHelp').textContent=t('Your final files are ready.','Je definitieve bestanden staan klaar.');$('downloadLabel').textContent=o.download_label||o.delivery_format||t('Final delivery','Definitieve oplevering');btn.href=o.download_url;btn.classList.remove('hidden')}else{dl.classList.add('locked');btn.classList.add('hidden');$('downloadHelp').textContent=t('Your download unlocks when the order is completed.','Je download wordt beschikbaar zodra de bestelling is voltooid.')}renderMessages(data.messages);renderReview(data.review)}
async function fetchAndRender(){const data=await call('get');render(data);return data}
function clearPaidCart(){try{localStorage.removeItem('damion_cart');localStorage.removeItem('damion_pending_order')}catch(_){}}
async function waitForPayment(){if(paymentPoll)return;let tries=0;const run=async()=>{tries++;try{const data=await fetchAndRender();const status=data.order&&data.order.status;if(status==='Paid'||status==='Completed'){clearPaidCart();clearInterval(paymentPoll);paymentPoll=null;return}if(status==='Payment failed'){clearInterval(paymentPoll);paymentPoll=null;return}if(tries>=12){clearInterval(paymentPoll);paymentPoll=null;$('etaText').textContent=t('Payment is still being confirmed. Refresh this page in a moment.','De betaling wordt nog bevestigd. Vernieuw deze pagina over een moment.')}}catch(_){if(tries>=12){clearInterval(paymentPoll);paymentPoll=null}}};await run();if(!paymentPoll&&tries<12)paymentPoll=setInterval(run,1800)}
async function loadOrder(){token=(new URLSearchParams(location.search).get('token')||($('tokenInput')?$('tokenInput').value:'')||localStorage.getItem('damion_order_token')||'').trim();if(!token)return;try{$('tokenInput').value=token;const data=await fetchAndRender();localStorage.setItem('damion_order_token',token);if(data.order&&(data.order.status==='Paid'||data.order.status==='Completed'))clearPaidCart();const fromPayment=new URLSearchParams(location.search).get('payment')==='return';if(fromPayment&&data.order&&data.order.status==='Pending payment')waitForPayment()}catch(err){$('orderRoom').classList.add('hidden');$('orderEmpty').classList.remove('hidden');$('orderEmpty').innerHTML=`<h2>${t("We couldn't open that order",'Deze bestelling kon niet worden geopend')}</h2><p>${esc(err.message)}</p>`}}
$('lookupForm')?.addEventListener('submit',e=>{e.preventDefault();token=$('tokenInput').value.trim();if(token)location.href=`/order?token=${encodeURIComponent(token)}`});
$('messageForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=$('messageInput'),message=input.value.trim();if(!message)return;const btn=e.submitter;btn.disabled=true;try{await call('message',{message});input.value='';const data=await call('get');renderMessages(data.messages)}catch(err){alert(err.message)}finally{btn.disabled=false}});
document.querySelectorAll('#reviewStars button').forEach(b=>b.addEventListener('click',()=>{if($('reviewText').disabled)return;currentRating=Number(b.dataset.rating);document.querySelectorAll('#reviewStars button').forEach(x=>x.classList.toggle('active',Number(x.dataset.rating)<=currentRating))}));
$('reviewButton')?.addEventListener('click',async()=>{const text=$('reviewText').value.trim();$('reviewButton').disabled=true;try{await call('review',{rating:currentRating,review:text});$('reviewStatus').textContent=t('Thanks — your review was saved.','Bedankt — je beoordeling is opgeslagen.')}catch(err){$('reviewStatus').textContent=err.message}finally{$('reviewButton').disabled=false}});
document.addEventListener('dm:languagechange',()=>{if(currentOrder)fetchAndRender().catch(()=>{})});
loadOrder();